import type { Locale } from '../types'

export const copy = {
  ru: {
    skip: 'Перейти к содержанию', contact: 'Контакты', resume: 'Резюме', resumeDownload: 'Резюме', resumeUnavailable: 'Резюме будет добавлено перед публикацией', themeToggle: 'Переключить тему', language: 'Выбор языка',
    navProduct: 'Продукт', navDesign: 'Дизайн', navAutomation: 'Автоматизация', navAnalytics: 'Аналитика',
    heroEyebrow: 'AI PRODUCT BUILDER / ЦИФРОВЫЕ СИСТЕМЫ', heroTitle: 'Я проектирую и запускаю цифровые системы, в которых продуктовая логика, визуальный опыт, автоматизация и данные работают как единое целое.', heroSubtitle: 'От архитектуры продукта и интерфейсов до AI-процессов, commerce-систем и аналитики.', heroPrimary: 'ИССЛЕДОВАТЬ СИСТЕМУ', heroSecondary: 'СМОТРЕТЬ ПРОЕКТЫ', openDirectionPage: 'Открыть направление', viewCases: 'Смотреть кейсы →',
    featured: 'Избранные кейсы', more: 'Ещё проекты', expertise: 'Что я создаю', whatIBuildEyebrow: '02 · СИСТЕМЫ И РЕЗУЛЬТАТЫ', whatIBuildIntro: 'Четыре взаимосвязанных слоя — от продуктовой структуры до измеримого решения.', process: 'Процесс работы', experience: 'Опыт', education: 'Образование',
    openCase: 'Открыть кейс →', openProject: 'Смотреть проект →', back: '← Вернуться на главную', next: 'Следующий проект',
    challenge: 'Задача', scope: 'Объём работы', approach: 'Процесс', result: 'Текущий статус',
    contactEyebrow: '07 · КОНТАКТ', mobileContactEyebrow: '08 · КОНТАКТ', contactHeading: 'Связаться', contactIntro: 'Открыта к проектам и ролям в продукте, дизайне и AI-автоматизации — на стыке UX, технологий и данных. Расскажите о задаче: обычно отвечаю в течение одного рабочего дня.', mobileContactIntro: 'Открыта к проектам и ролям в продукте, дизайне и AI-автоматизации. Обычно отвечаю в течение одного рабочего дня.', copyEmail: 'Скопировать email', availability: 'ДОСТУПНА ДЛЯ УДАЛЁННЫХ ПРОЕКТОВ', contactClosing: 'ПРОДУКТ · UX/UI · AI · ДАННЫЕ',
    downloadResume: 'Скачать резюме (PDF) ↓', formHeading: 'Написать сообщение', formDescription: 'Коротко опишите проект, роль или задачу.',
    name: 'Имя', namePlaceholder: 'Как к вам обращаться?', contactField: 'Email или Telegram', contactPlaceholder: 'email@example.com или @username', message: 'Сообщение', messagePlaceholder: 'Расскажите о проекте, роли или задаче', website: 'Сайт', send: 'Отправить сообщение →', sending: 'Отправка…',
    requiredName: 'Укажите имя.', requiredContact: 'Укажите email или Telegram.', requiredMessage: 'Добавьте сообщение.', tooLong: 'Текст слишком длинный.', success: 'Сообщение отправлено. Спасибо!', configError: 'Отправка с сайта пока не настроена. Напишите мне по email или в Telegram.', sendError: 'Не удалось отправить сообщение. Напишите мне по email или в Telegram.',
    footer: '© 2026 Anna Gromyko · AI Product Builder', top: 'Наверх ↑', notFound: 'Страница не найдена', home: 'На главную', current: 'СЕЙЧАС', nav: 'Основная навигация', heroGroup: 'Профессиональные направления', facts: 'Ключевые факты',
    chapterNavigation: 'Навигация по разделам', goToChapter: 'Перейти к разделу', chapterOf: 'из', scrollExplore: 'ПРОКРУТИТЕ ДАЛЬШЕ', backToTop: 'НАВЕРХ', chapterHero: 'Главная', chapterDirections: 'Направления', chapterFeatured: 'Избранные кейсы', chapterProjects: 'Ещё проекты', chapterProcess: 'Процесс работы', chapterExpertise: 'Что я создаю', chapterExperience: 'Опыт и образование', chapterContact: 'Контакты',
    chooseDirection: 'Выбрать направление →', directionsEyebrow: '02 · ПРОФЕССИОНАЛЬНЫЙ ФОКУС', directionsHeading: 'Направления', directionsIntro: 'Выберите область, чтобы перейти к соответствующим кейсам.', openDirection: 'Открыть кейсы направления', selectedDirection: 'Выбрано направление',
  },
  en: {
    skip: 'Skip to content', contact: 'Contact', resume: 'Resume', resumeDownload: 'Resume', resumeUnavailable: 'The resume will be added before launch', themeToggle: 'Switch theme', language: 'Language selection',
    navProduct: 'Product', navDesign: 'Design', navAutomation: 'Automation', navAnalytics: 'Analytics',
    heroEyebrow: 'AI PRODUCT BUILDER / DIGITAL SYSTEMS', heroTitle: 'I design and ship digital systems where product logic, visual experience, automation and data work as one.', heroSubtitle: 'From product architecture and interfaces to AI workflows, commerce systems, and analytics.', heroPrimary: 'EXPLORE THE SYSTEM', heroSecondary: 'VIEW SELECTED WORK', openDirectionPage: 'Open direction', viewCases: 'View cases →',
    featured: 'Featured case studies', more: 'More projects', expertise: 'What I Build', whatIBuildEyebrow: '02 · SYSTEMS & OUTCOMES', whatIBuildIntro: 'Four connected layers — from product structure to an actionable decision.', process: 'Process', experience: 'Experience', education: 'Education',
    openCase: 'View case study →', openProject: 'View project →', back: '← Back to home', next: 'Next project',
    challenge: 'Challenge', scope: 'Scope', approach: 'Process', result: 'Current status',
    contactEyebrow: '07 · CONTACT', mobileContactEyebrow: '08 · CONTACT', contactHeading: 'Let’s talk', contactIntro: 'Open to product, design, and AI automation projects and roles at the intersection of UX, technology, and data. Tell me about the opportunity — I usually reply within one business day.', mobileContactIntro: 'Open to projects and roles in product, design, and AI automation. I usually reply within one business day.', copyEmail: 'Copy email', availability: 'AVAILABLE FOR REMOTE PROJECTS', contactClosing: 'PRODUCT · UX/UI · AI · DATA',
    downloadResume: 'Download resume (PDF) ↓', formHeading: 'Send a message', formDescription: 'Briefly describe the project, role, or task.',
    name: 'Name', namePlaceholder: 'How should I address you?', contactField: 'Email or Telegram', contactPlaceholder: 'email@example.com or @username', message: 'Message', messagePlaceholder: 'Tell me about the project, role, or task', website: 'Website', send: 'Send message →', sending: 'Sending…',
    requiredName: 'Enter your name.', requiredContact: 'Enter an email or Telegram handle.', requiredMessage: 'Add a message.', tooLong: 'This text is too long.', success: 'Message sent. Thank you!', configError: 'Message delivery is not configured yet. Please contact me by email or Telegram.', sendError: 'The message could not be sent. Please contact me by email or Telegram.',
    footer: '© 2026 Anna Gromyko · AI Product Builder', top: 'Back to top ↑', notFound: 'Page not found', home: 'Go home', current: 'CURRENT', nav: 'Main navigation', heroGroup: 'Professional focus areas', facts: 'Key facts',
    chapterNavigation: 'Chapter navigation', goToChapter: 'Go to chapter', chapterOf: 'of', scrollExplore: 'SCROLL TO EXPLORE', backToTop: 'BACK TO TOP', chapterHero: 'Home', chapterDirections: 'Focus areas', chapterFeatured: 'Featured case studies', chapterProjects: 'More projects', chapterProcess: 'Process', chapterExpertise: 'What I Build', chapterExperience: 'Experience and education', chapterContact: 'Contact',
    chooseDirection: 'Choose a direction →', directionsEyebrow: '02 · PROFESSIONAL FOCUS', directionsHeading: 'Focus areas', directionsIntro: 'Choose an area to explore the relevant case studies.', openDirection: 'Open case studies for', selectedDirection: 'Selected focus',
  },
} as const

export type Translation = (typeof copy)[Locale]
